"""Add_grafana_metrics

Revision ID: 45e7c21939f9
Revises: da7ba2831ad8
Create Date: 2026-09-22 13:16:28.378265
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e7c21939f9'
down_revision: Union[str, None] = 'da7ba2831ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_snapshots', sa.Column('memory_total_bytes', sa.Float(), nullable=True))
    op.add_column('metric_snapshots', sa.Column('memory_available_bytes', sa.Float(), nullable=True))
    op.add_column('metric_snapshots', sa.Column('disk_total_bytes', sa.Float(), nullable=True))
    op.add_column('metric_snapshots', sa.Column('disk_free_bytes', sa.Float(), nullable=True))
    op.add_column('metric_snapshots', sa.Column('network_receive_rate', sa.Float(), nullable=True))
    op.add_column('metric_snapshots', sa.Column('network_transmit_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric_snapshots', 'network_transmit_rate')
    op.drop_column('metric_snapshots', 'network_receive_rate')
    op.drop_column('metric_snapshots', 'disk_free_bytes')
    op.drop_column('metric_snapshots', 'disk_total_bytes')
    op.drop_column('metric_snapshots', 'memory_available_bytes')
    op.drop_column('metric_snapshots', 'memory_total_bytes')
    # ### end Alembic commands ###
