"""add ssh_user to targets

Revision ID: f04f458aef3f
Revises: 6ef7bfff0c45
Create Date: 2026-09-19 00:08:04.458033
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04f458aef3f'
down_revision: Union[str, None] = '6ef7bfff0c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('ssh_user', sa.String(length=50), nullable=False, server_default='youssef'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('targets', 'ssh_user')
    # ### end Alembic commands ###
